SELECT 'CREATE DATABASE nombre_de_la_base_de_datos'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'tienda');
DROP TABLE IF EXISTS "categorias";
DROP TABLE IF EXISTS "funkos";
CREATE TABLE "public"."categorias" (
                                       "id" uuid NOT NULL,
                                       "categoria" character varying(255) NOT NULL,
                                       "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                       "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
                                       "is_deleted" boolean DEFAULT false NOT NULL,
                                       CONSTRAINT "categorias_pkey" PRIMARY KEY ("id"),
                                       CONSTRAINT "categorias_categoria_key" UNIQUE ("categoria")
);

CREATE TABLE "public"."funkos" (
                                   "id" bigint GENERATED BY DEFAULT AS IDENTITY,
                                   "nombre" character varying(255) NOT NULL,
                                   "precio" double precision DEFAULT 0.0 NOT NULL,
                                   "cantidad" integer DEFAULT 0 NOT NULL,
                                   "imagen" text DEFAULT 'https://via.placeholder.com/150' NOT NULL,
                                   "is_deleted" boolean DEFAULT false NOT NULL,
                                   "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
                                   "categoria_id" uuid,
                                   CONSTRAINT "funkos_pkey" PRIMARY KEY ("id"),
                                   CONSTRAINT "funkos_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias" ("id") ON DELETE CASCADE
);
-- Inserción de categorías
INSERT INTO "categorias" ("id", "categoria", "created_at", "updated_at", "is_deleted")
VALUES
    ('d69cf3db-b77d-4181-b3cd-5ca8107fb6a9', 'disney', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('6dbcbf5e-8e1c-47cc-8578-7b0a33ebc154', 'marvel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('9def16db-362b-44c4-9fc9-77117758b5b0', 'superhéroe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('8c5c06ba-49d6-46b6-85cc-8246c0f362bc', 'otros', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);

-- Inserción de Funkos en cada categoría
INSERT INTO "funkos" ("nombre", "precio", "cantidad", "categoria_id", "created_at", "updated_at", "is_deleted")
VALUES
    ('mickey mouse', 20.0, 10, 'd69cf3db-b77d-4181-b3cd-5ca8107fb6a9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('iron man', 25.0, 8, '6dbcbf5e-8e1c-47cc-8578-7b0a33ebc154', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('spider-man', 18.0, 12, '9def16db-362b-44c4-9fc9-77117758b5b0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    ('funko genérico', 15.0, 15, '8c5c06ba-49d6-46b6-85cc-8246c0f362bc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);